// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10-devel
// 	protoc        (unknown)
// source: v1/schema.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ticker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Pair          string                 `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	Bid           float64                `protobuf:"fixed64,3,opt,name=bid,proto3" json:"bid,omitempty"`
	BidSize       float64                `protobuf:"fixed64,4,opt,name=bid_size,json=bidSize,proto3" json:"bid_size,omitempty"`
	Ask           float64                `protobuf:"fixed64,5,opt,name=ask,proto3" json:"ask,omitempty"`
	AskSize       float64                `protobuf:"fixed64,6,opt,name=ask_size,json=askSize,proto3" json:"ask_size,omitempty"`
	EventTime     int64                  `protobuf:"varint,7,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticker) Reset() {
	*x = Ticker{}
	mi := &file_v1_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker) ProtoMessage() {}

func (x *Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_v1_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker.ProtoReflect.Descriptor instead.
func (*Ticker) Descriptor() ([]byte, []int) {
	return file_v1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Ticker) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Ticker) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Ticker) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *Ticker) GetBidSize() float64 {
	if x != nil {
		return x.BidSize
	}
	return 0
}

func (x *Ticker) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *Ticker) GetAskSize() float64 {
	if x != nil {
		return x.AskSize
	}
	return 0
}

func (x *Ticker) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

type Calculations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        float64                `protobuf:"fixed64,1,opt,name=volume,proto3" json:"volume,omitempty"`                           // Min(AskSize, BidSize)
	PriceDiff     float64                `protobuf:"fixed64,2,opt,name=price_diff,json=priceDiff,proto3" json:"price_diff,omitempty"`    // BidPrice - AskPrice
	PriceAvg      float64                `protobuf:"fixed64,3,opt,name=price_avg,json=priceAvg,proto3" json:"price_avg,omitempty"`       // (AskPrice + BidPrice) / 2
	Spread        float64                `protobuf:"fixed64,4,opt,name=spread,proto3" json:"spread,omitempty"`                           // PriceDiff * Volume
	SpreadPct     float64                `protobuf:"fixed64,5,opt,name=spread_pct,json=spreadPct,proto3" json:"spread_pct,omitempty"`    // PriceDiff / PriceAvg
	BidFee        float64                `protobuf:"fixed64,6,opt,name=bid_fee,json=bidFee,proto3" json:"bid_fee,omitempty"`             // BidFeeRate * BidPrice * Volume
	AskFee        float64                `protobuf:"fixed64,7,opt,name=ask_fee,json=askFee,proto3" json:"ask_fee,omitempty"`             // AskFeeRate * AskPrice * Volume
	ProfitLoss    float64                `protobuf:"fixed64,8,opt,name=profit_loss,json=profitLoss,proto3" json:"profit_loss,omitempty"` // Spread - BidFee - AskFee
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Calculations) Reset() {
	*x = Calculations{}
	mi := &file_v1_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Calculations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calculations) ProtoMessage() {}

func (x *Calculations) ProtoReflect() protoreflect.Message {
	mi := &file_v1_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calculations.ProtoReflect.Descriptor instead.
func (*Calculations) Descriptor() ([]byte, []int) {
	return file_v1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Calculations) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Calculations) GetPriceDiff() float64 {
	if x != nil {
		return x.PriceDiff
	}
	return 0
}

func (x *Calculations) GetPriceAvg() float64 {
	if x != nil {
		return x.PriceAvg
	}
	return 0
}

func (x *Calculations) GetSpread() float64 {
	if x != nil {
		return x.Spread
	}
	return 0
}

func (x *Calculations) GetSpreadPct() float64 {
	if x != nil {
		return x.SpreadPct
	}
	return 0
}

func (x *Calculations) GetBidFee() float64 {
	if x != nil {
		return x.BidFee
	}
	return 0
}

func (x *Calculations) GetAskFee() float64 {
	if x != nil {
		return x.AskFee
	}
	return 0
}

func (x *Calculations) GetProfitLoss() float64 {
	if x != nil {
		return x.ProfitLoss
	}
	return 0
}

type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                       // offset id
	Pair          string                 `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`                                    // asset pair to buy/sell
	AskExchange   string                 `protobuf:"bytes,3,opt,name=ask_exchange,json=askExchange,proto3" json:"ask_exchange,omitempty"`   // buy exchange
	AskPrice      float64                `protobuf:"fixed64,4,opt,name=ask_price,json=askPrice,proto3" json:"ask_price,omitempty"`          // buy price
	AskSize       float64                `protobuf:"fixed64,5,opt,name=ask_size,json=askSize,proto3" json:"ask_size,omitempty"`             // buy available quantity
	AskTime       int64                  `protobuf:"varint,6,opt,name=ask_time,json=askTime,proto3" json:"ask_time,omitempty"`              // buy ticker timestamp
	AskFeeRate    float64                `protobuf:"fixed64,7,opt,name=ask_fee_rate,json=askFeeRate,proto3" json:"ask_fee_rate,omitempty"`  // buy exchange fee rate
	BidExchange   string                 `protobuf:"bytes,8,opt,name=bid_exchange,json=bidExchange,proto3" json:"bid_exchange,omitempty"`   // sell exchange
	BidPrice      float64                `protobuf:"fixed64,9,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`          // sell price
	BidSize       float64                `protobuf:"fixed64,10,opt,name=bid_size,json=bidSize,proto3" json:"bid_size,omitempty"`            // sell available quantity
	BidTime       int64                  `protobuf:"varint,11,opt,name=bid_time,json=bidTime,proto3" json:"bid_time,omitempty"`             // sell ticker timestamp
	BidFeeRate    float64                `protobuf:"fixed64,12,opt,name=bid_fee_rate,json=bidFeeRate,proto3" json:"bid_fee_rate,omitempty"` // sell exchange fee rate
	Timestamp     int64                  `protobuf:"varint,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                        // Min(AskTime, BidTime)
	Calculations  *Calculations          `protobuf:"bytes,14,opt,name=calculations,proto3" json:"calculations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_v1_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_v1_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_v1_schema_proto_rawDescGZIP(), []int{2}
}

func (x *Match) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Match) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Match) GetAskExchange() string {
	if x != nil {
		return x.AskExchange
	}
	return ""
}

func (x *Match) GetAskPrice() float64 {
	if x != nil {
		return x.AskPrice
	}
	return 0
}

func (x *Match) GetAskSize() float64 {
	if x != nil {
		return x.AskSize
	}
	return 0
}

func (x *Match) GetAskTime() int64 {
	if x != nil {
		return x.AskTime
	}
	return 0
}

func (x *Match) GetAskFeeRate() float64 {
	if x != nil {
		return x.AskFeeRate
	}
	return 0
}

func (x *Match) GetBidExchange() string {
	if x != nil {
		return x.BidExchange
	}
	return ""
}

func (x *Match) GetBidPrice() float64 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *Match) GetBidSize() float64 {
	if x != nil {
		return x.BidSize
	}
	return 0
}

func (x *Match) GetBidTime() int64 {
	if x != nil {
		return x.BidTime
	}
	return 0
}

func (x *Match) GetBidFeeRate() float64 {
	if x != nil {
		return x.BidFeeRate
	}
	return 0
}

func (x *Match) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Match) GetCalculations() *Calculations {
	if x != nil {
		return x.Calculations
	}
	return nil
}

type ProfitableMatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	PeriodStart   int64                  `protobuf:"varint,5,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodProfit  float64                `protobuf:"fixed64,6,opt,name=period_profit,json=periodProfit,proto3" json:"period_profit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfitableMatchesResponse) Reset() {
	*x = ProfitableMatchesResponse{}
	mi := &file_v1_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfitableMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfitableMatchesResponse) ProtoMessage() {}

func (x *ProfitableMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfitableMatchesResponse.ProtoReflect.Descriptor instead.
func (*ProfitableMatchesResponse) Descriptor() ([]byte, []int) {
	return file_v1_schema_proto_rawDescGZIP(), []int{3}
}

func (x *ProfitableMatchesResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *ProfitableMatchesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ProfitableMatchesResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ProfitableMatchesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ProfitableMatchesResponse) GetPeriodStart() int64 {
	if x != nil {
		return x.PeriodStart
	}
	return 0
}

func (x *ProfitableMatchesResponse) GetPeriodProfit() float64 {
	if x != nil {
		return x.PeriodProfit
	}
	return 0
}

type Exchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TakerFee      float64                `protobuf:"fixed64,3,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	MakerFee      float64                `protobuf:"fixed64,4,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exchange) Reset() {
	*x = Exchange{}
	mi := &file_v1_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exchange) ProtoMessage() {}

func (x *Exchange) ProtoReflect() protoreflect.Message {
	mi := &file_v1_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exchange.ProtoReflect.Descriptor instead.
func (*Exchange) Descriptor() ([]byte, []int) {
	return file_v1_schema_proto_rawDescGZIP(), []int{4}
}

func (x *Exchange) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Exchange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exchange) GetTakerFee() float64 {
	if x != nil {
		return x.TakerFee
	}
	return 0
}

func (x *Exchange) GetMakerFee() float64 {
	if x != nil {
		return x.MakerFee
	}
	return 0
}

var File_v1_schema_proto protoreflect.FileDescriptor

const file_v1_schema_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/schema.proto\x12\x06api.v1\"\xb1\x01\n" +
	"\x06Ticker\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x12\n" +
	"\x04pair\x18\x02 \x01(\tR\x04pair\x12\x10\n" +
	"\x03bid\x18\x03 \x01(\x01R\x03bid\x12\x19\n" +
	"\bbid_size\x18\x04 \x01(\x01R\abidSize\x12\x10\n" +
	"\x03ask\x18\x05 \x01(\x01R\x03ask\x12\x19\n" +
	"\bask_size\x18\x06 \x01(\x01R\aaskSize\x12\x1d\n" +
	"\n" +
	"event_time\x18\a \x01(\x03R\teventTime\"\xec\x01\n" +
	"\fCalculations\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\x01R\x06volume\x12\x1d\n" +
	"\n" +
	"price_diff\x18\x02 \x01(\x01R\tpriceDiff\x12\x1b\n" +
	"\tprice_avg\x18\x03 \x01(\x01R\bpriceAvg\x12\x16\n" +
	"\x06spread\x18\x04 \x01(\x01R\x06spread\x12\x1d\n" +
	"\n" +
	"spread_pct\x18\x05 \x01(\x01R\tspreadPct\x12\x17\n" +
	"\abid_fee\x18\x06 \x01(\x01R\x06bidFee\x12\x17\n" +
	"\aask_fee\x18\a \x01(\x01R\x06askFee\x12\x1f\n" +
	"\vprofit_loss\x18\b \x01(\x01R\n" +
	"profitLoss\"\xb3\x03\n" +
	"\x05Match\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04pair\x18\x02 \x01(\tR\x04pair\x12!\n" +
	"\fask_exchange\x18\x03 \x01(\tR\vaskExchange\x12\x1b\n" +
	"\task_price\x18\x04 \x01(\x01R\baskPrice\x12\x19\n" +
	"\bask_size\x18\x05 \x01(\x01R\aaskSize\x12\x19\n" +
	"\bask_time\x18\x06 \x01(\x03R\aaskTime\x12 \n" +
	"\fask_fee_rate\x18\a \x01(\x01R\n" +
	"askFeeRate\x12!\n" +
	"\fbid_exchange\x18\b \x01(\tR\vbidExchange\x12\x1b\n" +
	"\tbid_price\x18\t \x01(\x01R\bbidPrice\x12\x19\n" +
	"\bbid_size\x18\n" +
	" \x01(\x01R\abidSize\x12\x19\n" +
	"\bbid_time\x18\v \x01(\x03R\abidTime\x12 \n" +
	"\fbid_fee_rate\x18\f \x01(\x01R\n" +
	"bidFeeRate\x12\x1c\n" +
	"\ttimestamp\x18\r \x01(\x03R\ttimestamp\x128\n" +
	"\fcalculations\x18\x0e \x01(\v2\x14.api.v1.CalculationsR\fcalculations\"\xd0\x01\n" +
	"\x19ProfitableMatchesResponse\x12'\n" +
	"\amatches\x18\x01 \x03(\v2\r.api.v1.MatchR\amatches\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12!\n" +
	"\fperiod_start\x18\x05 \x01(\x03R\vperiodStart\x12#\n" +
	"\rperiod_profit\x18\x06 \x01(\x01R\fperiodProfit\"h\n" +
	"\bExchange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttaker_fee\x18\x03 \x01(\x01R\btakerFee\x12\x1b\n" +
	"\tmaker_fee\x18\x04 \x01(\x01R\bmakerFeeB\"Z github.com/jimtang2/bc-go/pkg/pbb\x06proto3"

var (
	file_v1_schema_proto_rawDescOnce sync.Once
	file_v1_schema_proto_rawDescData []byte
)

func file_v1_schema_proto_rawDescGZIP() []byte {
	file_v1_schema_proto_rawDescOnce.Do(func() {
		file_v1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_schema_proto_rawDesc), len(file_v1_schema_proto_rawDesc)))
	})
	return file_v1_schema_proto_rawDescData
}

var file_v1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_schema_proto_goTypes = []any{
	(*Ticker)(nil),                    // 0: api.v1.Ticker
	(*Calculations)(nil),              // 1: api.v1.Calculations
	(*Match)(nil),                     // 2: api.v1.Match
	(*ProfitableMatchesResponse)(nil), // 3: api.v1.ProfitableMatchesResponse
	(*Exchange)(nil),                  // 4: api.v1.Exchange
}
var file_v1_schema_proto_depIdxs = []int32{
	1, // 0: api.v1.Match.calculations:type_name -> api.v1.Calculations
	2, // 1: api.v1.ProfitableMatchesResponse.matches:type_name -> api.v1.Match
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_schema_proto_init() }
func file_v1_schema_proto_init() {
	if File_v1_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_schema_proto_rawDesc), len(file_v1_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_schema_proto_goTypes,
		DependencyIndexes: file_v1_schema_proto_depIdxs,
		MessageInfos:      file_v1_schema_proto_msgTypes,
	}.Build()
	File_v1_schema_proto = out.File
	file_v1_schema_proto_goTypes = nil
	file_v1_schema_proto_depIdxs = nil
}
